stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    outs:
    - data/images
  train:
    cmd: python src/train.py
    deps:
    - data/images
    - src/train.py
    outs:
    - models/model.pkl
    - models/model.pth
    plots:
    - metrics/confusion_matrix.png
    - metrics/finetune_results.png
    - metrics/top_losses.png
  test:
    cmd: python src/test.py
    deps:
    - models/model.pkl
    - models/model.pth
    - src/test.py
